/*
 * File: HelloApp/controller/HelloController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext.direct.Manager.addProvider(Ext.app.REMOTING_API);
Ext.define('MyApp.controller.HelloController', {
	extend : 'Ext.app.Controller',

	onHelloButtonClick : function(button, e, options) {
		console.log("click");

		var window = Ext.getCmp('HelloPanel'), name = window.getComponent(
				'NameTextField').getValue();

		var callback = function(result, e) {
			Ext.MessageBox.alert('Server:', result);
		};

		helloDemoService.doHello(name, callback);

	},

	init : function(application) {
		this.control({
			"button#HelloButton" : {
				click : this.onHelloButtonClick
			}
		});
	}

});
